[phases.setup]
nixPkgs = ["openssl", "openssl.dev", "pkg-config"]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[phases.start]
cmd = "npm run start:railway"

[variables]
NODE_ENV = "production"
OPENSSL_LIB_DIR = "/nix/store/*/lib"
OPENSSL_INCLUDE_DIR = "/nix/store/*/include"
