[phases.setup]
nixPkgs = ["...", "openssl"]

[phases.build]
cmds = [
  "npm ci",
  "npm run build",
  "npx prisma generate"
]

[phases.start]
cmd = "npm run start:railway"

[variables]
NODE_ENV = "production"
